### ISSUE TITLE
nativescript-searchable-select nativescript 8 compatibility

### ISSUE THREAD

**Issue by comporell** [OPADA-Eng/ticnat-ns-plugins#3]
Hello,

When I try nativescript-searchable-select plugin with  "@nativescript/core": "~8.0.0", I receive this error whenever I click on a selectText button. Is this plugin ns 8 compatible? I am trying to migrate my app, this is the only hold back atm.

Best Regards,

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method getView failed
System.err: Error: Parsing XML at 1:1
System.err:  > Module 'StackLayout' not found for element 'StackLayout'.
System.err:    > com.tns.NativeScriptException: Failed to find module: "@nativescript/core/ui", relative to: app/tns_modules/
System.err:
System.err: StackTrace:
System.err: ScopeError(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:115782:9)
System.err:     at PositionErrorFormat(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:90912:16)
System.err:     at (file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:90897:32)
System.err:     at (file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:117596:13)
System.err:     at EasySAXParser.parse(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:84950:23)
System.err:     at parse(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:117639:22)
System.err:     at parse(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:90903:27)
System.err:     at parseInternal(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:90871:11)
System.err:     at parse(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:90739:37)
System.err:     at createView(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:105931:74)
System.err:     at ListViewAdapter.getView(file:///data/user/0/org.nativescript.Sistem/files/app/vendor.js:105834:29)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.android.widget.BaseAdapter_vendor_105777_28_ListViewAdapter.getView(BaseAdapter_vendor_105777_28_
ListViewAdapter.java:39)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2435)
System.err:     at android.widget.ListView.makeAndAddView(ListView.java:2082)
System.err:     at android.widget.ListView.fillDown(ListView.java:799)
System.err:     at android.widget.ListView.fillFromTop(ListView.java:861)
System.err:     at android.widget.ListView.layoutChildren(ListView.java:1844)
System.err:     at android.widget.AbsListView.onLayout(AbsListView.java:2232)
System.err:     at android.view.View.layout(View.java:23147)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6475)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err:     at android.view.View.layout(View.java:23147)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6475)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err:     at android.view.View.layout(View.java:23147)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6475)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:23147)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6475)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:23147)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6475)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
System.err:     at android.view.View.layout(View.java:23147)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6475)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:873)
System.err:     at android.view.View.layout(View.java:23147)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6475)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3852)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3263)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2257)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8796)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1140)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:962)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:887)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1125)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:263)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:8246)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by OPADA-Eng** [comment]
Hi,
I haven't yet tested or upgraded the plugins to ns8 if you could give a hand with that I appreciate it, or until I get some free time.

**Comment by comporell** [comment]
> 
> 
> Hi,
> I haven't yet tested or upgraded the plugins to ns8 if you could give a hand with that I appreciate it, or until I get some free time.

Hello Opada, apparently the plugin works fine with ns8. But currently entry points bundle should be added to the project till they are added to the new webpack. Details below:
https://github.com/nstudio/nativescript-plugins/issues/48#issuecomment-846400767

**Comment by OPADA-Eng** [comment]
@comporell 
Thanks for the solution, Can you make a PR?
